### ISSUE TITLE
dodac abstrakty UBS

### ISSUE THREAD

**Issue by MarcinKosinski** [whyRconf/abstrakty#10]

**Comment by MarcinKosinski** [comment]
@krzyslom myślisz ze uda się dodać opisy UBS które się niedawno pojawiły w formularzu :)? Mogą być dodane tutaj w nowym folderze, bo i tak będziemy grupować obecnie zgłoszone prezentacje w sesje , jak na planie

**Comment by krzyslom** [comment]
Nie przeczytałem zawczasu i dodałem luzem.
