### ISSUE TITLE
Dodać abstrakt pozostałych zaproszonych gości

### ISSUE THREAD

**Issue by MarcinKosinski** [whyRconf/abstrakty#4]

**Comment by MarcinKosinski** [comment]
@krzyslom mógłbym Cię prosić o dodanie 4 ostatnich wykładów plenarnych (obecnie posortowany jest plik - więc 4 ostatnie zgłoszenia), z formularza rejestracyjnego do tego repozytorium? Wtedy też do tych 4 osób może dobrze wysłać mail z informacją, że dotarły ich abstrakty na repo i że tutaj np. mogą zgłaszać  na GitHubie poprawki?

**Comment by krzyslom** [comment]
@MarcinKosinski Done, closing.

**Comment by MarcinKosinski** [comment]
Thank you!

2017-06-26 23:18 GMT+02:00 Krzysztof Słomczyński <notifications@github.com>:
